name: kafka-cluster

networks:
  inner-cluster-communication:

volumes:
  kafka-data:

services:
  kafka:
    image: "bitnami/kafka:latest"
    networks:
      - inner-cluster-communication
    ports:
      - "9095:9095"
    volumes:
      - kafka-data:/bitnami/kafka
    environment:
      # Node configuration
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"

      # Listener configurations
      KAFKA_CFG_LISTENERS: "BROKER://:9092,CONTROLLER://:9093,INTERNAL://:9094,EXTERNAL://:9095"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "BROKER://kafka:9092,INTERNAL://kafka:9094,EXTERNAL://localhost:9095"

      # Inter-broker communication
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "BROKER"

      # Controller configuration
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"

      # Client configuration
      KAFKA_CLIENT_LISTENER_NAME: "EXTERNAL"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-broker-api-versions.sh --bootstrap-server kafka:9092 || exit 1",
        ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 10s

  kafka-ui:
    image: "kafbat/kafka-ui:latest"
    networks:
      - inner-cluster-communication
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9094"
    depends_on:
      kafka:
        condition: service_healthy
